"""Remove user_id field from book_copies

Revision ID: 9d7321065db1
Revises: d61e1bf037f7
Create Date: 2025-07-24 22:54:11.237926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d7321065db1'
down_revision: Union[str, Sequence[str], None] = 'd61e1bf037f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('FK__book_copi__user___3E52440B'), 'book_copies', type_='foreignkey')
    op.drop_column('book_copies', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_copies', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('FK__book_copi__user___3E52440B'), 'book_copies', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
