"""Remove user_id field from book_copies

Revision ID: d61e1bf037f7
Revises: 073bd82f7579
Create Date: 2025-07-24 22:53:33.463997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd61e1bf037f7'
down_revision: Union[str, Sequence[str], None] = '073bd82f7579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book_copies', 'status',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Enum('AVAILABLE', 'LOANED', 'LOST', name='bookcopystatus'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book_copies', 'status',
               existing_type=sa.Enum('AVAILABLE', 'LOANED', 'LOST', name='bookcopystatus'),
               type_=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    # ### end Alembic commands ###
